# Functions, Conditions, Iterations

In [4]:
def HelloWorldXY(x,y):
    if x < 10:
        print('X was < 10')
    elif x < 20:
        print('X was >= 10 but < 20')
    else:
        print('X was >= 20')
    return x + y

for i in range(10, 30, 5):
    print('Now running with i: {}'.format(i))
    r = HelloWorldXY(i,i)
    print('Result from HelloWorld {}'.format(r))

Now running with i: 10
X was >= 10 but < 20
Result from HelloWorld 20
Now running with i: 15
X was >= 10 but < 20
Result from HelloWorld 30
Now running with i: 20
X was >= 20
Result from HelloWorld 40
Now running with i: 25
X was >= 20
Result from HelloWorld 50


In [9]:
print(HelloWorldXY(10,5))

X was >= 10 but < 20
15


# Iteration 

In [20]:
print('iterating over range 4')
for i in range(4):
    print(i)
    
print('iterate over list')
for i in [0,1,2,3]:
    print(i)
    
print('while works')    
i = 0
while i < 4:
    print(i)
    i += 1

iterating over range 4
0
1
2
3
iterate over list
0
1
2
3
while works
0
1
2
3


In [21]:
# Break
while True:
    print('nik')
    break

nik


# Numpy and List

In [26]:
import numpy as np

a = np.array(['nik','gawai'])
a = np.append(a,'!')

print(a)

for i in a:
    print(i)



['nik' 'gawai' '!']
nik
gawai
!


In [35]:
b = np.array([0,1,4,3,2])

print(np.max(b))
print(np.average(b))
print(np.min(b))
print(np.argmax(b))

print('max: {}'.format(np.max(b)))
print('average: {}'.format(np.average(b)))
print('min: {}'.format(np.min(b)))
print('max index:{}'.format(np.argmax(b)))

4
2.0
0
2
max: 4
average: 2.0
min: 0
max index:2


In [36]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [40]:
c = np.random.rand(3,4)
print(c)

[[0.57549501 0.58999437 0.91936896 0.49900618]
 [0.42730913 0.89388224 0.04860883 0.36029315]
 [0.66140072 0.35160549 0.70790856 0.98456741]]


# Shape

In [45]:
print('shape of a:{}'.format(a.shape))
print('shape of b:{}'.format(b.shape))
print('shape of c:{}'.format(c.shape))

shape of a:(3,)
shape of b:(5,)
shape of c:(3, 4)


In [48]:
!ls -l
!pwd

total 8
-rw-rw-r-- 1 nikhil nikhil 6282 Oct  6 14:45 'intro to colab.ipynb'
/home/nikhil/JupyTensorflow


In [50]:
!pwd
!cd /
!ls -l
print('nik')

/home/nikhil/JupyTensorflow
total 8
-rw-rw-r-- 1 nikhil nikhil 6282 Oct  6 14:45 'intro to colab.ipynb'
nik
